# Generated by Django 6.1 on 2026-08-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_reports/%Y/%m/%d/')),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('report_date', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_model_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.CharField(blank=True, max_length=20)),
                ('bus_no', models.CharField(blank=True, max_length=50)),
                ('mech', models.CharField(blank=True, max_length=100)),
                ('work_done', models.TextField(blank=True)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('raw_text', models.TextField(blank=True)),
                ('row_order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='extractor.workreport')),
            ],
            options={
                'ordering': ['row_order'],
            },
        ),
    ]
